

-- 테이블 생성
-- 테이블명: PROF
CREATE TABLE PROF
( PF_ID     VARCHAR2(20)    
, PF_NAME   VARCHAR2(20)    CONSTRAINT  PF_PF_NAME_NN  NOT NULL
, PF_SSN    VARCHAR2(20)    CONSTRAINT  PF_PF_SSN_NN   NOT NULL
, PF_PW     VARCHAR2(20)    CONSTRAINT  PF_PF_PW_NN    NOT NULL
, PF_DATE   DATE            CONSTRAINT  PROF_PF_DATE_NN  NOT NULL
, CONSTRAINT PF_PF_ID_PK PRIMARY KEY(PF_ID)
, CONSTRAINT  PROF_PFSSN_UK UNIQUE(PF_SSN)
);


-- 테이블 생성
-- 테이블명: STUD
CREATE TABLE STUD
( ST_ID     VARCHAR2(20)
, ST_PW     VARCHAR2(20)    CONSTRAINT ST_ST_PW_NN NOT NULL
, ST_NAME   VARCHAR2(20)    CONSTRAINT ST_ST_NAME_NN NOT NULL
, ST_SSN    VARCHAR2(20)    CONSTRAINT ST_ST_SSN_NN NOT NULL
, ST_DATE   DATE            CONSTRAINT ST_ST_DATE_NN NOT NULL
, CONSTRAINT ST_ST_ID_PK PRIMARY KEY(ST_ID)
, CONSTRAINT  ST_ST_SSN_UK UNIQUE(ST_SSN)
);


-- 테이블 생성
-- 테이블명: COURSE
CREATE TABLE COURSE
( CR_CODE   VARCHAR2(20)    
, CR_NAME   VARCHAR2(20)    CONSTRAINT CR_CR_NAME_NN NOT NULL
, CONSTRAINT CR_CR_CODE_PK PRIMARY KEY(CR_CODE)
);
-- 테이블 생성
-- 테이블명: SUB
CREATE TABLE SUB
( SUB_CODE  VARCHAR2(20)    
, SUB_NAME  VARCHAR2(20)    CONSTRAINT SUB_SUB_NAME_NN NOT NULL
, CONSTRAINT SUB_SUB_CODE_PK  PRIMARY KEY(SUB_CODE)
);


-- 테이블 생성
-- 테이블명: TEXTBOOK
CREATE TABLE TEXTBOOK
( TB_CODE   VARCHAR2(20)    
, TB_NAME   VARCHAR2(20)    CONSTRAINT TB_TB_NAME_NN  NOT NULL
, CONSTRAINT TB_TB_CODE_PK PRIMARY KEY(TB_CODE)
);


-- 테이블 생성
-- 테이블명: CLASS
CREATE TABLE CLASS
( CL_CODE   VARCHAR2(20)
, CL_NAME   VARCHAR2(20)    CONSTRAINT CL_CL_NAME_NN NOT NULL
, CONSTRAINT CL_CL_CODE_PK PRIMARY KEY(CL_CODE)
);


-- 테이블 생성
-- 테이블명: ADMIN_ROLE
CREATE TABLE ADMIN_ROLE
( AR_CODE   VARCHAR2(20)
, AR_NAME   VARCHAR2(20)    CONSTRAINT AR_AR_NAME_NN NOT NULL
, CONSTRAINT AR_AR_CODE_PK PRIMARY KEY(AR_CODE)
);


-- 테이블 생성
-- 테이블명: DROP_REASON
CREATE TABLE DROP_REASON
( DR_CODE   VARCHAR2(20)
, DR_REASON VARCHAR2(20)    CONSTRAINT DR_DR_REASON_NN NOT NULL
, CONSTRAINT DR_DR_CODE_PK PRIMARY KEY(DR_CODE)
);








