SELECT USER
FROM DUAL;
--==>> SCOTT


CREATE SEQUENCE ST_SEQ
INCREMENT BY 1
START WITH 114
NOCACHE;
--==>> Sequence ST_SEQ이(가) 생성되었습니다.

-- 프로시저 생성
-- 프로시저명: PRC_ST_C
-- STUD테이블에 INSERT - 최종관리자만 가능 (이름, 주민번호)
CREATE OR REPLACE PROCEDURE PRC_ST_C
( P_ST_NAME   IN  STUD.ST_NAME%TYPE
, P_ST_SSN    IN  STUD.ST_SSN%TYPE
)
IS
    V_SEQ   NUMBER(5);
BEGIN

    SELECT ST_SEQ.NEXTVAL INTO V_SEQ
    FROM DUAL;
    INSERT INTO STUD(ST_ID, ST_PW, ST_NAME, ST_SSN)
    VALUES('ST'||V_SEQ, SUBSTR(P_ST_SSN,8),P_ST_NAME,P_ST_SSN);
    
END;


-- 프로시저 생성
-- 프로시저명: PRC_ST_U
-- STUD테이블에 UPDATE - 관리자만 가능 (학생아이디, 이름, 주민번호, 비밀번호)
CREATE OR REPLACE PROCEDURE PRC_ST_U
( P_ST_ID   IN  STUD.ST_ID%TYPE
, P_ST_NAME IN  STUD.ST_NAME%TYPE
, P_ST_SSN  IN  STUD.ST_SSN%TYPE
, P_ST_PW   IN  STUD.ST_PW%TYPE
)
IS
BEGIN
    UPDATE STUD
    SET ST_NAME = NVL(P_ST_NAME, ST_NAME), ST_SSN = NVL(P_ST_SSN, ST_SSN), ST_PW = NVL(P_ST_PW, ST_PW)
    WHERE ST_ID = P_ST_ID;
END;



-- 프로시저 생성
-- 프로시저명: PRC_ST_D
-- STUD테이블에 DELETE - 관리자만 가능 (학생아이디)
CREATE OR REPLACE PROCEDURE PRC_ST_D
(P_ST_ID IN STUD.ST_ID%TYPE)
IS
BEGIN
    DELETE
    FROM STUD
    WHERE ST_ID = P_ST_ID;
END;

CREATE SEQUENCE GR_SEQ
INCREMENT BY 1
START WITH 003
NOCACHE;
--==>> Sequence GR_SEQ이(가) 생성되었습니다.

-- 프로시저 생성
-- 프로시저명: PRC_GR_C
-- GRADE 테이블에 INSERT - 관리자, 교수자만 가능 (수강신청코드, 개설과목코드, 출결점수, 필기점수, 실기점수)
CREATE OR REPLACE PROCEDURE PRC_GR_C
( P_ER_CODE     IN  GRADE.ER_CODE%TYPE
, P_OS_CODE     IN  GRADE.OS_CODE%TYPE
, P_ATT_SCORE   IN  GRADE.ATT_SCORE%TYPE
, P_WRT_SCORE   IN  GRADE.WRT_SCORE%TYPE
, P_PRC_SCORE   IN  GRADE.PRC_SCORE%TYPE
)
IS
    V_SEQ NUMBER(5);
BEGIN
    SELECT GR_SEQ.NEXTVAL INTO V_SEQ
    FROM DUAL;
    
    INSERT INTO GRADE(GR_CODE, ER_CODE, OS_CODE, ATT_SCORE, WRT_SCORE, PRC_SCORE)
    VALUES('GR'||V_SEQ, P_ER_CODE, P_OS_CODE, P_ATT_SCORE, P_WRT_SCORE, P_PRC_SCORE);
END;


-- 프로시저 생성
-- 프로시저명: PRC_GR_U
-- GRADE 테이블에 UPDATE - 관리자, 교수자만 가능(성적코드, 수강신청코드, 개설과목코드, 출결점수, 필기점수, 실기점수)
CREATE OR REPLACE PROCEDURE PRC_GR_U
( P_GR_CODE     IN  GRADE.GR_CODE%TYPE
, P_ER_CODE     IN  GRADE.ER_CODE%TYPE
, P_OS_CODE     IN  GRADE.OS_CODE%TYPE
, P_ATT_SCORE   IN  GRADE.ATT_SCORE%TYPE
, P_WRT_SCORE   IN  GRADE.WRT_SCORE%TYPE
, P_PRC_SCORE   IN  GRADE.PRC_SCORE%TYPE
)
IS
BEGIN
    
    UPDATE GRADE
    SET ER_CODE = NVL(P_ER_CODE, ER_CODE), OS_CODE = NVL(P_OS_CODE, OS_CODE), ATT_SCORE = NVL(P_ATT_SCORE, ATT_SCORE), WRT_SCORE = NVL(P_WRT_SCORE, WRT_SCORE), PRC_SCORE = NVL(P_PRC_SCORE, PRC_SCORE)
    WHERE GR_CODE = P_GR_CODE;
END;

















